FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip \
    curl \
    libpng-dev \
    libzip-dev \
    libonig-dev 


RUN docker-php-ext-install \
    pdo \
    pdo_mysql \
    mbstring \
    zip    


COPY --from=composer:latest /usr/bin/composer  /usr/bin/composer

WORKDIR /var/www





